colors:
- blue
- orange
- green
fit_labels:
- $\textrm{DIS prior } 0.5\; {\rm GeV}^2$
- $\textrm{DIS prior } 1.0\; {\rm GeV}^2$
- $\textrm{DIS prior } 1.5\; {\rm GeV}^2$
fitnames:
- 250625-ac-03-pc-low_cuts-05
- 250618-ac-01-low_cuts-pc
- 250625-ac-04-pc-low_cuts-15
hatchs:
- /
- x
- //
